url: "http://thelastseenfestival.com" # the base hostname & protocol for your site
baseurl: "/" # the subpath of your site, e.g. /blog/

title: The Last Seen Comedy Festival
description: A festival of provocative and original comedy that captures a sense of eccentricity, unconventional style, and irreverent behavior.

exclude: ["_assets", "gulp", ".gitignore", "gulpfile.js", "package.json", "node_modules", "README.md"]
keep_files: ["assets"]

future: true
timezone: America/New_York

collections:
  shows:
    output: true
  performers:
    output: true
  workshops:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      image: "assets/images/last-seen-festival.png"
  -
    scope:
      path: ""
      type: shows
    values:
      layout: detail
      image_path: "assets/images/shows/"
  -
    scope:
      path: ""
      type: performers
    values:
      layout: detail
      image_path: "assets/images/performers/"

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
